-- Initial schema for the Workout Tracker.
-- Written to run on both PostgreSQL (production) and H2 in PostgreSQL mode (development/tests).

CREATE TABLE users (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                VARCHAR(20)  NOT NULL,
    email                   VARCHAR(50)  NOT NULL,
    password                VARCHAR(120) NOT NULL,
    first_name              VARCHAR(50),
    last_name               VARCHAR(50),
    date_of_birth           TIMESTAMP(6),
    gender                  VARCHAR(255),
    height_cm               INTEGER,
    weight_kg               DOUBLE PRECISION,
    activity_level          VARCHAR(255),
    account_non_expired     BOOLEAN,
    account_non_locked      BOOLEAN,
    credentials_non_expired BOOLEAN,
    enabled                 BOOLEAN,
    created_at              TIMESTAMP(6) NOT NULL,
    updated_at              TIMESTAMP(6),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT ck_users_activity_level CHECK (activity_level IN
        ('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', 'EXTRA_ACTIVE'))
);

CREATE TABLE exercises (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(100) NOT NULL,
    description          TEXT,
    category             VARCHAR(255) NOT NULL,
    primary_muscle_group VARCHAR(255) NOT NULL,
    difficulty_level     VARCHAR(255),
    equipment_required   VARCHAR(255),
    instructions         TEXT,
    image_url            VARCHAR(255),
    video_url            VARCHAR(255),
    is_active            BOOLEAN,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6),
    CONSTRAINT ck_exercises_category CHECK (category IN
        ('CARDIO', 'STRENGTH_TRAINING', 'FLEXIBILITY', 'BALANCE', 'SPORTS_SPECIFIC',
         'FUNCTIONAL_FITNESS', 'PLYOMETRIC', 'REHABILITATION', 'MOBILITY', 'CORE_STABILITY')),
    CONSTRAINT ck_exercises_difficulty_level CHECK (difficulty_level IN
        ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')),
    CONSTRAINT ck_exercises_primary_muscle_group CHECK (primary_muscle_group IN
        ('CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'QUADRICEPS', 'HAMSTRINGS',
         'GLUTES', 'CALVES', 'ABS', 'OBLIQUES', 'LOWER_BACK', 'FULL_BODY', 'CARDIOVASCULAR',
         'LEGS', 'ARMS', 'CORE', 'UPPER_BODY', 'LOWER_BODY'))
);

CREATE TABLE exercise_secondary_muscles (
    exercise_id  BIGINT NOT NULL,
    muscle_group VARCHAR(255),
    CONSTRAINT fk_secondary_muscles_exercise FOREIGN KEY (exercise_id) REFERENCES exercises (id),
    CONSTRAINT ck_secondary_muscles_muscle_group CHECK (muscle_group IN
        ('CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'QUADRICEPS', 'HAMSTRINGS',
         'GLUTES', 'CALVES', 'ABS', 'OBLIQUES', 'LOWER_BACK', 'FULL_BODY', 'CARDIOVASCULAR',
         'LEGS', 'ARMS', 'CORE', 'UPPER_BODY', 'LOWER_BODY'))
);

CREATE TABLE workouts (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT       NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    description           VARCHAR(500),
    scheduled_date_time   TIMESTAMP(6),
    started_at            TIMESTAMP(6),
    completed_at          TIMESTAMP(6),
    status                VARCHAR(255) NOT NULL,
    duration_minutes      INTEGER,
    total_calories_burned INTEGER,
    notes                 VARCHAR(1000),
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6),
    CONSTRAINT fk_workouts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_workouts_status CHECK (status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE workout_exercises (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id       BIGINT  NOT NULL,
    exercise_id      BIGINT  NOT NULL,
    sets             INTEGER NOT NULL,
    repetitions      INTEGER NOT NULL,
    weight_kg        DOUBLE PRECISION,
    distance_km      DOUBLE PRECISION,
    duration_seconds INTEGER,
    calories_burned  INTEGER,
    rest_seconds     INTEGER,
    exercise_order   INTEGER,
    notes            VARCHAR(500),
    completed        BOOLEAN,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6),
    CONSTRAINT fk_workout_exercises_workout FOREIGN KEY (workout_id) REFERENCES workouts (id),
    CONSTRAINT fk_workout_exercises_exercise FOREIGN KEY (exercise_id) REFERENCES exercises (id),
    CONSTRAINT ck_workout_exercises_sets CHECK (sets >= 1),
    CONSTRAINT ck_workout_exercises_repetitions CHECK (repetitions >= 1)
);

-- PostgreSQL does not index foreign keys automatically; these back the common lookups.
CREATE INDEX idx_secondary_muscles_exercise_id ON exercise_secondary_muscles (exercise_id);
CREATE INDEX idx_workouts_user_id ON workouts (user_id);
CREATE INDEX idx_workout_exercises_workout_id ON workout_exercises (workout_id);
CREATE INDEX idx_workout_exercises_exercise_id ON workout_exercises (exercise_id);
